import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('aapl_dirty.csv')
#print(df.info())
df_clean = df.ffill()
#print(df_clean.info())
#print(df_clean.head(7))
df_clean['Daily_Return'] = df_clean['Close'].pct_change()
print(df_clean[['Date', 'Close', 'Daily_Return']].head(7))
df_clean['Fast_SMA'] = df_clean['Close'].rolling(window=2).mean()
#print(df_clean[['Date', 'Close', 'Fast_SMA']].head(7))
df_clean['Slow_SMA'] = df_clean['Close'].rolling(window=4).mean()
#print(df_clean[['Date', 'Close', 'Slow_SMA']].head(7)) 
df_clean['Signal'] = np.where(df_clean['Fast_SMA'] > df_clean['Slow_SMA'], 1, -1)
print(df_clean[['Date', 'Fast_SMA', 'Slow_SMA', 'Signal']].head(7))
df_clean['Strategy_Return'] = df_clean['Daily_Return'] * df_clean['Signal'].shift(1)
#print(df_clean[['Date', 'Daily_Return', 'Signal', 'Strategy_Return']].head(7))
df_clean['Market_Growth'] = (1 + df_clean['Daily_Return']).cumprod()
df_clean['Strategy_Growth'] = (1 + df_clean['Strategy_Return']).cumprod()
print(df_clean[['Date', 'Market_Growth', 'Strategy_Growth']].tail(5))

df_clean.set_index('Date', inplace=True)
df_clean[['Market_Growth', 'Strategy_Growth']].plot(figsize=(10, 6))
plt.title('Market Growth vs Strategy Growth')
plt.xlabel('Date')
plt.ylabel('Growth')
plt.show()